apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kit

resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - scc.yaml
  - scc-rolebinding.yaml
  - configmap.yaml
  - build.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kit
      app.kubernetes.io/part-of: kit
    includeSelectors: true
